### ISSUE TITLE
setup.py references wrong GitHub project

### ISSUE THREAD

**Issue by dgabbe** [eric-s-s/bind_json_error_handlers#3]
Is this a typo:

https://github.com/eric-s-s/bind_json_error_handlers/blob/b56c7f8f83cb9e3f4055356ce5aea8586dc04bdf/setup.py#L16

Was expecting:

 ```http
url='https://github.com/eric-s-s/bind_json_error_handlers```

**Comment by eric-s-s** [comment]
this issue is now resolved by PR #6
